version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "net.bytebuddy:byte-buddy"
      - dependency-name: "net.bytebuddy:byte-buddy-agent"