name: Gradle Build

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Non-device tests
        run: ./gradlew check
      - name: On-Device Tests
        run: adb connect android-emulator:5555 && adb wait-for-device && ./gradlew connectedCheck
      - name: Upload Test Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/build/reports/coverage/androidTest/debug/report.xml
