name: Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: temurin

      - name: Build with Gradle
        run: ./gradlew build
      - name: Generate Test Report
        run: ./gradlew jacocoTestReport
      - name: Upload Test Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/build/jacoco/jacoco.xml